language: node_js

notifications:
  email: false

node_js:
  - v7
  - v6
  - v5
  - v4

branches:
  only:
    - master

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
